package io.jethro.app.backtest;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Real historical daily bars for the walk-forward replay (ADR-0027 point 2): loaded from a
 * checked-in/on-host JSON file generated by {@code scripts/fetch_bars.py} (Stooq — the same
 * source the sim calibration uses), so the replay runs on REAL closes without a runtime
 * network dependency. Format, exact decimals as strings (invariant 1 at the boundary):
 *
 * <pre>  {"AAPL": [["2024-01-02", "185.64"], ["2024-01-03", "184.25"], ...], "ES": [...]}</pre>
 *
 * Bars must be date-ascending per instrument; the loader validates order and parses prices
 * as {@link BigDecimal}. A missing file is a normal state (the platform hasn't fetched bars
 * yet) — callers surface "no historical data" honestly, never an empty backtest.
 */
public final class HistoricalBars {

    public record Bar(LocalDate day, BigDecimal close) {
    }

    private HistoricalBars() {
    }

    public static Map<String, List<Bar>> load(Path file) throws java.io.IOException {
        JsonNode root = new ObjectMapper().readTree(Files.readString(file));
        Map<String, List<Bar>> out = new LinkedHashMap<>();
        root.fields().forEachRemaining(entry -> {
            List<Bar> bars = new ArrayList<>();
            LocalDate previous = null;
            for (JsonNode row : entry.getValue()) {
                LocalDate day = LocalDate.parse(row.get(0).asText());
                if (previous != null && !day.isAfter(previous)) {
                    throw new IllegalArgumentException(
                            "bars for " + entry.getKey() + " not date-ascending at " + day);
                }
                bars.add(new Bar(day, new BigDecimal(row.get(1).asText())));
                previous = day;
            }
            out.put(entry.getKey(), bars);
        });
        return out;
    }

    /**
     * The same bar map read from the DB {@code daily_close} SEED history instead of a file (ADR-0128).
     * This is the ONE history source of truth — Tiingo-seeded and periodically refreshed by
     * {@code HistorySeeder} — so the walk-forward runs on the same rolling window that feeds VaR /
     * vol-targeting / the hedge covariance, and there is no separate (and, per the Stooq 404s, unreliable)
     * bars file to keep in sync. SEED closes are uniformly scaled, and the backtest's PnL is
     * scale-invariant (notional × return), so the edge verdict is unaffected. Ascending by day per name.
     */
    public static Map<String, List<Bar>> fromDailyClose(
            org.springframework.jdbc.core.JdbcTemplate jdbc, String feedMode) {
        Map<String, List<Bar>> out = new LinkedHashMap<>();
        jdbc.query("select instrument, day, close from daily_close where feed_mode = ? order by instrument, day",
                rs -> {
                    String id = rs.getString("instrument");
                    LocalDate day = rs.getDate("day").toLocalDate();
                    BigDecimal close = rs.getBigDecimal("close");
                    out.computeIfAbsent(id, k -> new ArrayList<>()).add(new Bar(day, close));
                }, feedMode);
        return out;
    }
}
