package io.jethro.app.backtest;

import io.jethro.app.order.ExecutionProperties;
import io.jethro.app.strategy.StrategyProperties;
import io.jethro.trading.riskpnl.InstrumentRef;
import io.jethro.trading.riskpnl.InstrumentRefSource;

import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Runs the walk-forward replay (ADR-0027) over the on-host historical bars file
 * ({@code jethro.backtest.bars-path}, generated by {@code scripts/fetch_bars.py}) with the
 * LIVE sizing/cost config, so its verdict measures the same economics as everything else.
 * No bars file is a normal, honestly-reported state — the platform never fabricates history.
 */
public final class WalkForwardService {

    private final WalkForwardEngine engine = new WalkForwardEngine();
    private final StrategyProperties strategy;
    private final ExecutionProperties execution;
    private final InstrumentRefSource refs;
    private final Path barsPath;

    public WalkForwardService(StrategyProperties strategy, ExecutionProperties execution,
                              InstrumentRefSource refs, String barsPath) {
        this.strategy = strategy;
        this.execution = execution;
        this.refs = refs;
        this.barsPath = Path.of(barsPath);
    }

    /** @return empty when no bars file exists yet (fetch_bars.py hasn't been run). */
    public Optional<WalkForwardEngine.Result> run(String algo, Integer fitDays, Integer evalDays)
            throws java.io.IOException {
        if (!Files.exists(barsPath)) {
            return Optional.empty();
        }
        Map<String, List<HistoricalBars.Bar>> bars = HistoricalBars.load(barsPath);
        Map<String, BigDecimal> multipliers = new LinkedHashMap<>();
        bars.keySet().forEach(id -> multipliers.put(id,
                refs.find(id).map(InstrumentRef::multiplier).orElse(BigDecimal.ONE)));
        String algoOrLive = algo != null && !algo.isBlank() ? algo.trim().toLowerCase()
                : strategy.algoOrDefault();
        var cfg = new WalkForwardEngine.Config(
                algoOrLive,
                fitDays != null && fitDays > 20 ? fitDays : 252,   // ~1y fit
                evalDays != null && evalDays > 5 ? evalDays : 63,  // ~1 quarter eval
                strategy.minSignalBpsOrDefault(),
                strategy.targetNotional(),
                strategy.maxOrderNotionalOrDefault(),
                strategy.maxPositionNotionalOrDefault(),
                strategy.allowShortOrDefault(),
                execution.perFillCostBps("EQUITY"),
                multipliers);
        return Optional.of(engine.run(bars, cfg));
    }

    public String barsPath() {
        return barsPath.toString();
    }
}
