[versions]
java = "21"
springBoot = "3.3.5"
avro = "1.12.0"
avroPlugin = "1.9.1"
junit = "5.11.3"
archunit = "1.3.0"
lmdbjava = "0.9.0"
jackson = "2.17.2"
kafka = "3.8.0"
postgresql = "42.7.4"
flyway = "10.20.1"
commonsMath = "3.6.1"
strata = "2.12.20"

[libraries]
commons-math = { module = "org.apache.commons:commons-math3", version.ref = "commonsMath" }
strata-measure = { module = "com.opengamma.strata:strata-measure", version.ref = "strata" }
avro = { module = "org.apache.avro:avro", version.ref = "avro" }
lmdbjava = { module = "org.lmdbjava:lmdbjava", version.ref = "lmdbjava" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "springBoot" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
spring-boot-starter-jdbc = { module = "org.springframework.boot:spring-boot-starter-jdbc", version.ref = "springBoot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
avro = { id = "com.github.davidmc24.gradle.plugin.avro", version.ref = "avroPlugin" }
